sfad

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -3,7 +3,7 @@ name: "build-debug"
 on:
   push:
     tags:
-      - 'v[0-9]+.[0-9]+.[0-9]+'
+      - '^v[0-9]+.[0-9]+.[0-9]+$'
 
 jobs:
   build:
@@ -11,18 +11,20 @@ jobs:
     steps:
       - name: Check out the repo
         uses: actions/checkout@v2
-#      - name: Get Latest Tag
-#        id: latesttag
-#        run: |
-#          git fetch --tags
-#          echo ::set-output name=TAG::$(git describe --tags `git rev-list --tags --max-count=1`)
-#      - name: Login to Docker Hub
-#        uses: docker/login-action@v3
-#        with:
-#          username: ${{ secrets.DOCKERHUB_USERNAME }}
-#          password: ${{ secrets.DOCKERHUB_TOKEN }}
-#      - uses: docker/build-push-action@v2
-#        with:
-#          push: true
-#          context: debug
-#          tags: seemscloud/debug:${{ steps.latesttag.outputs.TAG }}
+      - name: Get Latest Tag
+        id: latesttag
+        run: |
+          git fetch --tags
+          LATEST_TAG=$(git tag --sort=committerdate  | grep -Ei "^v[0-9]+.[0-9]+.[0-9]+$" | tail -1)
+          [ -z "${LATEST_TAG}" ] && echo "Failed on tag match.." && exit 100
+          echo ::set-output name=TAG::$(git describe --tags `git rev-list --tags --max-count=1`)
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_TOKEN }}
+      - uses: docker/build-push-action@v2
+        with:
+          push: true
+          context: debug
+          tags: seemscloud/debug:${{ steps.latesttag.outputs.TAG }}
